from Komodo_RPC import KomodoRPC

######################################
#   Project: Komodo RPC API (Python) #
#   Author: Vaibhav Murkute          #
######################################

komodo_rpc = KomodoRPC(rpc_port='15406', req_method='POST', rpc_username='user3263390897',
                        rpc_password='pass885b1d8131e0c2217a8ffbf5fe5ca34367af529a6d519abf8cbbbd16f8a1e36d30')

print('getwalletinfo: ')
result = komodo_rpc.getwalletinfo()
print(result)
print('backupwallet: ')
result = komodo_rpc.backupwallet('testwalletbackp')
print(result)
print('dumpprivkey: ')
result = komodo_rpc.dumpprivkey('RXdhZanPXDb4Yp675zxq2TspYvcNrGmKJR')
print(result)
print('getaccount: ')
result = komodo_rpc.getaccount('RXdhZanPXDb4Yp675zxq2TspYvcNrGmKJR')
print(result)
print('getbalance: ')
result = komodo_rpc.getbalance('RXdhZanPXDb4Yp675zxq2TspYvcNrGmKJR')
print(result)
print('getbalance: ')
result = komodo_rpc.getbalance('RXdhZanPXDb4Yp675zxq2TspYvcNrGmKJR')
print(result)
print('getnewaddress: ')
#result = komodo_rpc.getnewaddress()
print(result)
print('getrawchangeaddress: ')
result = komodo_rpc.getrawchangeaddress()
print(result)
print('getreceivedbyaddress: ')
result = komodo_rpc.getreceivedbyaddress('RXdhZanPXDb4Yp675zxq2TspYvcNrGmKJR')
print(result)
print('gettransaction: ')
result = komodo_rpc.gettransaction('ff2c4c0c0d55310c2f7e9105e2fdbdb1496049e1b7f193d7f69d7a5b662fc610')
print(result)
print('getunconfirmedbalance: ')
result = komodo_rpc.getunconfirmedbalance()
print(result)
print('importaddress: ')
result = komodo_rpc.importaddress('R9z796AehK5b6NCPeVkGUHSpJnawerf8oP', label='testing', rescan=False)
print(result)
print('importprivkey: ')
result = komodo_rpc.importprivkey('R9z796AehK5b6NCPeVkGUHSpJnawerf8oP', label='testing', rescan=False)
print(result)
print('importwallet: ')
#result = komodo_rpc.importwallet(path='')
print(result)
print('keypoolrefill: ')
result = komodo_rpc.keypoolrefill()
print(result)
print('listaddressgroupings: ')
result = komodo_rpc.listaddressgroupings()
print(result)
print('listlockunspent: ')
result = komodo_rpc.listlockunspent()
print(result)
print('listreceivedbyaddress: ')
result = komodo_rpc.listreceivedbyaddress(6,True, True)
print(result)
print('listsinceblock: ')
result = komodo_rpc.listsinceblock('',1)
print(result)
print('listtransactions: ')
result = komodo_rpc.listtransactions()
print(result)
print('listunspent: ')
result = komodo_rpc.listunspent(addresses=["RY5MZCNeyJSivCkDLWCA834XVqeWiZ99Ba", "RGcMHMkb3dfQ37cejpoZtkEkJgBiXmQDPz"])
print(result)
print('lockunspent: ')
#result = komodo_rpc.lockunspent(txid="ff2c4c0c0d55310c2f7e9105e2fdbdb1496049e1b7f193d7f69d7a5b662fc610")
print(result)
print('resendwallettransactions: ')
result = komodo_rpc.resendwallettransactions()
print(result)
print('sendmany: ')
#result = komodo_rpc.sendmany("", {"RY5MZCNeyJSivCkDLWCA834XVqeWiZ99Ba":0.01,"RGcMHMkb3dfQ37cejpoZtkEkJgBiXmQDPz":0.02}, 1, "testing")
print(result)
print('sendtoaddress: ')
#result = komodo_rpc.sendtoaddress(address="RY5MZCNeyJSivCkDLWCA834XVqeWiZ99Ba", amount=0.1, comment="Test", comment_to="", subtractFeeFromAmt=False)
print(result)
print('settxfee: ')
result = komodo_rpc.settxfee(amount=0.0001)
print(result)
print('signmessage: ')
result = komodo_rpc.signmessage(address="RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ", message="Test Message")
print(result)

# Network Commands:
print('addnode: ')
#result = komodo_rpc.addnode(node='192.168.0.4:4112', command='onetry')
print(result)
print('clearbanned: ')
result = komodo_rpc.clearbanned()
print(result)
print('disconnectnode: ')
#result = komodo_rpc.disconnectnode(node='192.168.0.4:4112')
print(result)
print('getaddednodeinfo: ')
result = komodo_rpc.getaddednodeinfo(node='192.168.0.4:4112')
print(result)
print('getconnectioncount: ')
result = komodo_rpc.getconnectioncount()
print(result)
print('getdeprecationinfo: ')
result = komodo_rpc.getdeprecationinfo()
print(result)
print('getnettotals: ')
result = komodo_rpc.getnettotals()
print(result)
print('getnetworkinfo: ')
result = komodo_rpc.getnetworkinfo()
print(result)
print('getpeerinfo: ')
result = komodo_rpc.getpeerinfo()
print(result)
print('listbanned: ')
result = komodo_rpc.listbanned()
print(result)
print('ping: ')
result = komodo_rpc.ping()
print(result)
print('setban: ')
#result = komodo_rpc.setban(ip='192.168.0.3/24', command='add', bantime=86400, absolute=False)
print(result)

########### Util Commands #################################
print('createmultisig: ')
result = komodo_rpc.createmultisig(keys=['RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ', 'RGcMHMkb3dfQ37cejpoZtkEkJgBiXmQDPz'], number_required=2)
print(result)
print('decodeccopret: ')
result = komodo_rpc.decodeccopret(scriptPubKey='76a914868494e200f3265e57cd75af0b81d9a1c28c598488ac')
print(result)
print('estimatefee: ')
result = komodo_rpc.estimatefee(num_blocks=2)
print(result)
print('estimatepriority: ')
result = komodo_rpc.estimatepriority(num_blocks=2)
print(result)
print('invalidateblock: ')
result = komodo_rpc.invalidateblock(block_hash='02f51fb2793b0728050c5e983ffed669594e0a2dda01dcb7a68d129fd87436e0')
print(result)
print('reconsiderblock: ')
result = komodo_rpc.reconsiderblock(block_hash='02f51fb2793b0728050c5e983ffed669594e0a2dda01dcb7a68d129fd87436e0')
print(result)
print('txnotarizedconfirmed: ')
result = komodo_rpc.txnotarizedconfirmed(tx_id='ff2c4c0c0d55310c2f7e9105e2fdbdb1496049e1b7f193d7f69d7a5b662fc610')
print(result)
print('validateaddress: ')
result = komodo_rpc.validateaddress(address='RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ')
print(result)
print('verifymessage: ')
result = komodo_rpc.verifymessage(signature='IHGQI9G1WpHBXqshBktuqXOJKRa6siPd+ZRWdBigZhZ6Mxdcz/qNMjyQRgZ2QKcSTNzL7tTC2A9TPfA0Xvc1M3c=', address='RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ', message='Test Message')
print(result)
print('z_validateaddress: ')
result = komodo_rpc.z_validateaddress(address='RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ')
print(result)
print('getaddressbalance: ')
result = komodo_rpc.getaddressbalance(addresses=["RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ"])
print(result)
print('getaddressdeltas: ')
result = komodo_rpc.getaddressdeltas(addresses=[""], start=1, end=200, chainInfo=True)
print(result)
print('getaddressmempool: ')
result = komodo_rpc.getaddressmempool(addresses=["RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ"])
print(result)
print('getaddresstxids: ')
result = komodo_rpc.getaddresstxids(addresses=["RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ"], start=1, end=200)
print(result)
print('getaddressutxos: ')
result = komodo_rpc.getaddressutxos(addresses=["RMYTT9gkYk6r5kCY8ttiWGmoihdts61kXZ"], chainInfo=True)
print(result)
print('getsnapshot: ')
result = komodo_rpc.getsnapshot(top=2)
print(result)

#################################################### Control Commands ##################################################################

print('getinfo: ')
result = komodo_rpc.getinfo()
print(result)
print('help: ')
result = komodo_rpc.help(command='getwalletinfo')
print(result)
print('stop: ')
result = komodo_rpc.stop()
print(result)
